version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    environment:
      NODE_ENV: development
      PORT: 8080
      MONGO_URI: mongodb://root:example@mongodb:27017/
      ACCESS_TOKEN_SECRET: secret123
      REFRESH_TOKEN_SECRET: secret123
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - express-mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    networks:
      - express-mongo
    volumes:
      - ./mongo_data:/data/db

networks:
  express-mongo:
volumes:
  mongo_data:
